# The name of your project
name = "meta-surfer"

# The build command
command = "npm run build"

# Directory where your built files are located
[build]
upload = { dir = "build" }

# Directory where your built files will be served from
[site]
bucket = "./build"

# Build output directory for Pages
pages_build_output_dir = "build"
